<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atividadeJava" nsURI="http://www.example.org/atividadeJava"
    nsPrefix="atividadeJava">
  <eClassifiers xsi:type="ecore:EClass" name="JPackage" eSuperTypes="#//JElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jelement" upperBound="-1"
        eType="#//JElement" containment="true" eOpposite="#//JElement/jpackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jpackage" eType="#//JPackage"
        eOpposite="#//JPackage/jelement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JClassifier" eSuperTypes="#//JElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JClass" eSuperTypes="#//JClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Vis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jfield" upperBound="-1"
        eType="#//JField" containment="true" eOpposite="#//JField/jclass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jmethod" upperBound="-1"
        eType="#//JMethod" containment="true" eOpposite="#//JMethod/jclass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JInterface" abstract="true" interface="true"
      eSuperTypes="#//JClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="JMethod" eSuperTypes="#//JElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jclass" eType="#//JClass"
        eOpposite="#//JClass/jmethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jparameter" upperBound="-1"
        eType="#//JParameter" containment="true" eOpposite="#//JParameter/jmethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Vis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JField" eSuperTypes="#//JElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jclass" eType="#//JClass"
        eOpposite="#//JClass/jfield"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Vis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JParameter" eSuperTypes="#//JElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jmethod" eType="#//JMethod"
        eOpposite="#//JMethod/jparameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="int" value="2"/>
    <eLiterals name="float" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Vis">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="input"/>
    <eLiterals name="output" value="1"/>
    <eLiterals name="inputOutput" value="2"/>
    <eLiterals name="return" value="3"/>
  </eClassifiers>
</ecore:EPackage>
