<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atividadeC" nsURI="http://www.example.org/atividadeC" nsPrefix="atividadeC">
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="res" eType="#//Reservada"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programa" eType="#//Programa"
        eOpposite="#//Programa/function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Struct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programa" upperBound="-1"
        eType="#//Programa" containment="true" eOpposite="#//Programa/struct"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="res" eType="#//Reservada"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="#//Programa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="res" eType="#//Reservada"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programa" eType="#//Programa"
        eOpposite="#//Programa/main"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Biblioteca">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programa" upperBound="-1"
        eType="#//Programa" containment="true" eOpposite="#//Programa/biblioteca"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//Lib"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programa">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biblioteca" eType="#//Biblioteca"
        eOpposite="#//Biblioteca/programa"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="struct" eType="#//Struct"
        eOpposite="#//Struct/programa"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true" eOpposite="#//Function/programa"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//Main" containment="true"
        eOpposite="#//Main/programa"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Lib">
    <eLiterals name="stdlib"/>
    <eLiterals name="stdio" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="int"/>
    <eLiterals name="float" value="1"/>
    <eLiterals name="char" value="2"/>
    <eLiterals name="boolean" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Reservada">
    <eLiterals name="printf"/>
    <eLiterals name="scanf" value="1"/>
  </eClassifiers>
</ecore:EPackage>
